version: '3'

# Load configuration in layers:
# 1. .env.example provides defaults (committed, works out-of-box)
# 2. .env.local overrides for individual developer needs (gitignored, optional)
dotenv:
  - .env.example
  - .env.local

includes:
  workspace: ../Taskfile.yaml
  mw: ./tasks/tasks.mw.yml
  brain: ./tasks/tasks.brain.yml
  mind: ./tasks/tasks.mind.yml
