version: 3

vars:
  HOST: localhost
  PORT: 8080
  TEMPL_DIR: ./internal/templates
  STATIC_DIR: ./static
  ASSETS_DIR: ./assets

tasks:
  live:go:
    desc: Live reload the go code
    cmds:
      - go run github.com/air-verse/air@latest

  live:templ:
    desc: Live reload the templates
    cmds:
      - go tool templ generate --watch --proxy="http://{{.HOST}}:{{.PORT}}"

  live:tailwindcss:
    desc: Live reload the tailwindcss styles
    cmds:
      - pnpm tailwindcss -i ./assets/css/input.css -o ./assets/css/main.css --watch

  live:
    desc: Live reload the go code, templates, and tailwindcss styles
    deps:
      - live:go
      - live:templ
      - live:tailwindcss

  # build/templates:
  #   desc: Build the templates
  #   cmds:
  #     - templ build -o ./tmp/templates.go -dir ${TEMPL_DIR}
  
  # build/assets:
  #   desc: Build the assets
  #   cmds:
  #     - go build -o ./tmp/assets.go -dir ${ASSETS_DIR}
