version: 3

env:
  PRODUCTION: false

vars:
  APP_PORT: 8080
  APP_CMD: go run ./cmd/mindweaver/main.go
  APP_HOST: localhost
  PROXY_PORT: 8081
  TEMPL_DIR: ./internal/templates
  TEMPL_OPEN_BROWSER: false
  DIST_DIR: ./dist
  STATIC_DIR: ./static
  ASSETS_DIR: ./assets

tasks:
  default:
    cmds:
      - live

  live:templ:
    desc: Live reload the templates
    cmds:
      - go tool templ generate --watch --proxy="http://{{.APP_HOST}}:{{.APP_PORT}}" --cmd="{{.APP_CMD}}" --proxybind="{{.APP_HOST}}" --proxyport="{{.PROXY_PORT}}" --open-browser="{{.TEMPL_OPEN_BROWSER}}"

  live:esbuild:
    desc: Bundle and watch JS/TS files
    env:
      APP_HOST: "{{.APP_HOST}}"
      PROXY_PORT: "{{.PROXY_PORT}}"
    cmds:
      - node build.js dev

  build:esbuild:
    desc: Build JS/TS files for production
    env:
      DEV: "false"
      PRODUCTION: true
    cmds:
      - node build.js build

  build:templ:
    desc: Build the templates
    env:
      PRODUCTION: true
    cmds:
      - go tool templ generate --cmd="{{.APP_CMD}}"

  build:go:
    desc: Build the Go binary
    env:
      PRODUCTION: true
    cmds:
      - go build -o bin/mindweaver ./cmd/mindweaver/main.go

  live:
    desc: Live reload the go code, templates, and assets
    deps:
      - build:utils
      - live:templ
      - live:esbuild

  build:
    desc: Build the go code, templates, and assets
    deps:
      - build:utils
      - build:esbuild
      - format:templ
      - build:templ
      - build:go

  format:templ:
    desc: Format all templ files
    cmds:
      - templ fmt {{.TEMPL_DIR}}

  build:utils:
    desc: Build utilities for tasks like copying assets, validating routes, etc
    cmds:
      - go run ./cmd/build/svg-icons.go
