// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assistants.sql

package store

import (
	"context"
	"database/sql"
)

const createAssistant = `-- name: CreateAssistant :execlastid

INSERT INTO assistants (name, description, provider_type, api_key, base_url, organization, llm_config, system_prompt_id, is_active)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type CreateAssistantParams struct {
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	ProviderType   string         `json:"provider_type"`
	ApiKey         sql.NullString `json:"api_key"`
	BaseUrl        string         `json:"base_url"`
	Organization   sql.NullString `json:"organization"`
	LlmConfig      string         `json:"llm_config"`
	SystemPromptID sql.NullInt64  `json:"system_prompt_id"`
	IsActive       sql.NullBool   `json:"is_active"`
}

// assistants.sql
// CRUD operations for assistants table
// Manages named AI assistants that users create
// Examples: "My Code Buddy", "Research Assistant", "Writing Helper"
func (q *Queries) CreateAssistant(ctx context.Context, arg CreateAssistantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAssistant,
		arg.Name,
		arg.Description,
		arg.ProviderType,
		arg.ApiKey,
		arg.BaseUrl,
		arg.Organization,
		arg.LlmConfig,
		arg.SystemPromptID,
		arg.IsActive,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteAssistantByID = `-- name: DeleteAssistantByID :exec
DELETE FROM assistants WHERE id = ?1
`

func (q *Queries) DeleteAssistantByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAssistantByID, id)
	return err
}

const getAssistantByID = `-- name: GetAssistantByID :one
SELECT id, name, description, provider_type, api_key, base_url, organization, llm_config, system_prompt_id, is_active, created_at, updated_at FROM assistants WHERE id = ?1
`

func (q *Queries) GetAssistantByID(ctx context.Context, id int64) (Assistant, error) {
	row := q.db.QueryRowContext(ctx, getAssistantByID, id)
	var i Assistant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProviderType,
		&i.ApiKey,
		&i.BaseUrl,
		&i.Organization,
		&i.LlmConfig,
		&i.SystemPromptID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssistantByName = `-- name: GetAssistantByName :one
SELECT id, name, description, provider_type, api_key, base_url, organization, llm_config, system_prompt_id, is_active, created_at, updated_at FROM assistants WHERE name = ?1 LIMIT 1
`

func (q *Queries) GetAssistantByName(ctx context.Context, name string) (Assistant, error) {
	row := q.db.QueryRowContext(ctx, getAssistantByName, name)
	var i Assistant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProviderType,
		&i.ApiKey,
		&i.BaseUrl,
		&i.Organization,
		&i.LlmConfig,
		&i.SystemPromptID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssistantWithPrompt = `-- name: GetAssistantWithPrompt :one

SELECT 
    a.id, a.name, a.description, a.provider_type, a.api_key, a.base_url, a.organization, a.llm_config, a.system_prompt_id, a.is_active, a.created_at, a.updated_at,
    p.id as prompt_id,
    p.title as prompt_title,
    p.content as prompt_content,
    p.category as prompt_category
FROM assistants a
LEFT JOIN prompts p ON a.system_prompt_id = p.id
WHERE a.id = ?1
`

type GetAssistantWithPromptRow struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	ProviderType   string         `json:"provider_type"`
	ApiKey         sql.NullString `json:"api_key"`
	BaseUrl        string         `json:"base_url"`
	Organization   sql.NullString `json:"organization"`
	LlmConfig      string         `json:"llm_config"`
	SystemPromptID sql.NullInt64  `json:"system_prompt_id"`
	IsActive       sql.NullBool   `json:"is_active"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	PromptID       sql.NullInt64  `json:"prompt_id"`
	PromptTitle    sql.NullString `json:"prompt_title"`
	PromptContent  sql.NullString `json:"prompt_content"`
	PromptCategory sql.NullString `json:"prompt_category"`
}

// ========================================
// Composite Queries - Assistants with Relations
// ========================================
func (q *Queries) GetAssistantWithPrompt(ctx context.Context, id int64) (GetAssistantWithPromptRow, error) {
	row := q.db.QueryRowContext(ctx, getAssistantWithPrompt, id)
	var i GetAssistantWithPromptRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProviderType,
		&i.ApiKey,
		&i.BaseUrl,
		&i.Organization,
		&i.LlmConfig,
		&i.SystemPromptID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromptID,
		&i.PromptTitle,
		&i.PromptContent,
		&i.PromptCategory,
	)
	return i, err
}

const listActiveAssistants = `-- name: ListActiveAssistants :many
SELECT id, name, description, provider_type, api_key, base_url, organization, llm_config, system_prompt_id, is_active, created_at, updated_at FROM assistants 
WHERE is_active = 1 
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAssistants(ctx context.Context) ([]Assistant, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAssistants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assistant
	for rows.Next() {
		var i Assistant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProviderType,
			&i.ApiKey,
			&i.BaseUrl,
			&i.Organization,
			&i.LlmConfig,
			&i.SystemPromptID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistants = `-- name: ListAssistants :many
SELECT id, name, description, provider_type, api_key, base_url, organization, llm_config, system_prompt_id, is_active, created_at, updated_at FROM assistants ORDER BY created_at DESC
`

func (q *Queries) ListAssistants(ctx context.Context) ([]Assistant, error) {
	rows, err := q.db.QueryContext(ctx, listAssistants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assistant
	for rows.Next() {
		var i Assistant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProviderType,
			&i.ApiKey,
			&i.BaseUrl,
			&i.Organization,
			&i.LlmConfig,
			&i.SystemPromptID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantsByProviderType = `-- name: ListAssistantsByProviderType :many
SELECT id, name, description, provider_type, api_key, base_url, organization, llm_config, system_prompt_id, is_active, created_at, updated_at FROM assistants 
WHERE provider_type = ?1 
ORDER BY created_at DESC
`

func (q *Queries) ListAssistantsByProviderType(ctx context.Context, providerType string) ([]Assistant, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantsByProviderType, providerType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assistant
	for rows.Next() {
		var i Assistant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProviderType,
			&i.ApiKey,
			&i.BaseUrl,
			&i.Organization,
			&i.LlmConfig,
			&i.SystemPromptID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAssistantActive = `-- name: SetAssistantActive :exec
UPDATE assistants
SET is_active = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type SetAssistantActiveParams struct {
	IsActive sql.NullBool `json:"is_active"`
	ID       int64        `json:"id"`
}

func (q *Queries) SetAssistantActive(ctx context.Context, arg SetAssistantActiveParams) error {
	_, err := q.db.ExecContext(ctx, setAssistantActive, arg.IsActive, arg.ID)
	return err
}

const updateAssistantByID = `-- name: UpdateAssistantByID :exec
UPDATE assistants
SET name = ?1,
    description = ?2,
    provider_type = ?3,
    api_key = ?4,
    base_url = ?5,
    organization = ?6,
    llm_config = ?7,
    system_prompt_id = ?8,
    is_active = ?9,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?10
`

type UpdateAssistantByIDParams struct {
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	ProviderType   string         `json:"provider_type"`
	ApiKey         sql.NullString `json:"api_key"`
	BaseUrl        string         `json:"base_url"`
	Organization   sql.NullString `json:"organization"`
	LlmConfig      string         `json:"llm_config"`
	SystemPromptID sql.NullInt64  `json:"system_prompt_id"`
	IsActive       sql.NullBool   `json:"is_active"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateAssistantByID(ctx context.Context, arg UpdateAssistantByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAssistantByID,
		arg.Name,
		arg.Description,
		arg.ProviderType,
		arg.ApiKey,
		arg.BaseUrl,
		arg.Organization,
		arg.LlmConfig,
		arg.SystemPromptID,
		arg.IsActive,
		arg.ID,
	)
	return err
}
