// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package store

import (
	"context"
	"database/sql"
)

const createConversation = `-- name: CreateConversation :execlastid

INSERT INTO conversations (title, assistant_id, conversation_type, linked_note_id, summary, metadata, is_active, last_activity)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type CreateConversationParams struct {
	Title            string         `json:"title"`
	AssistantID      int64          `json:"assistant_id"`
	ConversationType sql.NullString `json:"conversation_type"`
	LinkedNoteID     sql.NullInt64  `json:"linked_note_id"`
	Summary          sql.NullString `json:"summary"`
	Metadata         sql.NullString `json:"metadata"`
	IsActive         sql.NullBool   `json:"is_active"`
	LastActivity     sql.NullTime   `json:"last_activity"`
}

// conversations.sql
// CRUD operations for conversations table
// Manages chat sessions with assistants
// Timestamps managed by DB.
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createConversation,
		arg.Title,
		arg.AssistantID,
		arg.ConversationType,
		arg.LinkedNoteID,
		arg.Summary,
		arg.Metadata,
		arg.IsActive,
		arg.LastActivity,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteConversationByID = `-- name: DeleteConversationByID :exec
DELETE FROM conversations WHERE id = ?1
`

func (q *Queries) DeleteConversationByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConversationByID, id)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, title, assistant_id, conversation_type, linked_note_id, summary, metadata, is_active, last_activity, created_at, updated_at FROM conversations WHERE id = ?1
`

func (q *Queries) GetConversationByID(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AssistantID,
		&i.ConversationType,
		&i.LinkedNoteID,
		&i.Summary,
		&i.Metadata,
		&i.IsActive,
		&i.LastActivity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationWithAssistant = `-- name: GetConversationWithAssistant :one

SELECT 
    c.id, c.title, c.assistant_id, c.conversation_type, c.linked_note_id, c.summary, c.metadata, c.is_active, c.last_activity, c.created_at, c.updated_at,
    a.id as assistant_id,
    a.name as assistant_name,
    a.provider_type as assistant_provider_type
FROM conversations c
LEFT JOIN assistants a ON c.assistant_id = a.id
WHERE c.id = ?1
`

type GetConversationWithAssistantRow struct {
	ID                    int64          `json:"id"`
	Title                 string         `json:"title"`
	AssistantID           int64          `json:"assistant_id"`
	ConversationType      sql.NullString `json:"conversation_type"`
	LinkedNoteID          sql.NullInt64  `json:"linked_note_id"`
	Summary               sql.NullString `json:"summary"`
	Metadata              sql.NullString `json:"metadata"`
	IsActive              sql.NullBool   `json:"is_active"`
	LastActivity          sql.NullTime   `json:"last_activity"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	AssistantID_2         sql.NullInt64  `json:"assistant_id_2"`
	AssistantName         sql.NullString `json:"assistant_name"`
	AssistantProviderType sql.NullString `json:"assistant_provider_type"`
}

// ========================================
// Composite Queries - Conversations with Relations
// ========================================
func (q *Queries) GetConversationWithAssistant(ctx context.Context, id int64) (GetConversationWithAssistantRow, error) {
	row := q.db.QueryRowContext(ctx, getConversationWithAssistant, id)
	var i GetConversationWithAssistantRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AssistantID,
		&i.ConversationType,
		&i.LinkedNoteID,
		&i.Summary,
		&i.Metadata,
		&i.IsActive,
		&i.LastActivity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssistantID_2,
		&i.AssistantName,
		&i.AssistantProviderType,
	)
	return i, err
}

const getConversationWithDetails = `-- name: GetConversationWithDetails :one
SELECT 
    c.id, c.title, c.assistant_id, c.conversation_type, c.linked_note_id, c.summary, c.metadata, c.is_active, c.last_activity, c.created_at, c.updated_at,
    a.id as assistant_id,
    a.name as assistant_name,
    a.provider_type as assistant_provider_type,
    a.llm_config as assistant_llm_config,
    COUNT(m.id) as message_count
FROM conversations c
LEFT JOIN assistants a ON c.assistant_id = a.id
LEFT JOIN messages m ON c.id = m.conversation_id
WHERE c.id = ?1
GROUP BY c.id
`

type GetConversationWithDetailsRow struct {
	ID                    int64          `json:"id"`
	Title                 string         `json:"title"`
	AssistantID           int64          `json:"assistant_id"`
	ConversationType      sql.NullString `json:"conversation_type"`
	LinkedNoteID          sql.NullInt64  `json:"linked_note_id"`
	Summary               sql.NullString `json:"summary"`
	Metadata              sql.NullString `json:"metadata"`
	IsActive              sql.NullBool   `json:"is_active"`
	LastActivity          sql.NullTime   `json:"last_activity"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	AssistantID_2         sql.NullInt64  `json:"assistant_id_2"`
	AssistantName         sql.NullString `json:"assistant_name"`
	AssistantProviderType sql.NullString `json:"assistant_provider_type"`
	AssistantLlmConfig    sql.NullString `json:"assistant_llm_config"`
	MessageCount          int64          `json:"message_count"`
}

func (q *Queries) GetConversationWithDetails(ctx context.Context, id int64) (GetConversationWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getConversationWithDetails, id)
	var i GetConversationWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AssistantID,
		&i.ConversationType,
		&i.LinkedNoteID,
		&i.Summary,
		&i.Metadata,
		&i.IsActive,
		&i.LastActivity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssistantID_2,
		&i.AssistantName,
		&i.AssistantProviderType,
		&i.AssistantLlmConfig,
		&i.MessageCount,
	)
	return i, err
}

const getRecentConversations = `-- name: GetRecentConversations :many
SELECT id, title, assistant_id, conversation_type, linked_note_id, summary, metadata, is_active, last_activity, created_at, updated_at FROM conversations 
WHERE last_activity >= ?1
ORDER BY last_activity DESC
`

func (q *Queries) GetRecentConversations(ctx context.Context, sinceDate sql.NullTime) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, getRecentConversations, sinceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AssistantID,
			&i.ConversationType,
			&i.LinkedNoteID,
			&i.Summary,
			&i.Metadata,
			&i.IsActive,
			&i.LastActivity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveConversations = `-- name: ListActiveConversations :many
SELECT id, title, assistant_id, conversation_type, linked_note_id, summary, metadata, is_active, last_activity, created_at, updated_at FROM conversations 
WHERE is_active = 1 
ORDER BY created_at DESC
`

func (q *Queries) ListActiveConversations(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listActiveConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AssistantID,
			&i.ConversationType,
			&i.LinkedNoteID,
			&i.Summary,
			&i.Metadata,
			&i.IsActive,
			&i.LastActivity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT id, title, assistant_id, conversation_type, linked_note_id, summary, metadata, is_active, last_activity, created_at, updated_at FROM conversations ORDER BY created_at DESC
`

func (q *Queries) ListConversations(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AssistantID,
			&i.ConversationType,
			&i.LinkedNoteID,
			&i.Summary,
			&i.Metadata,
			&i.IsActive,
			&i.LastActivity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByAssistant = `-- name: ListConversationsByAssistant :many
SELECT id, title, assistant_id, conversation_type, linked_note_id, summary, metadata, is_active, last_activity, created_at, updated_at FROM conversations 
WHERE assistant_id = ?1 
ORDER BY created_at DESC
`

func (q *Queries) ListConversationsByAssistant(ctx context.Context, assistantID int64) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByAssistant, assistantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AssistantID,
			&i.ConversationType,
			&i.LinkedNoteID,
			&i.Summary,
			&i.Metadata,
			&i.IsActive,
			&i.LastActivity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByLinkedNote = `-- name: ListConversationsByLinkedNote :many
SELECT id, title, assistant_id, conversation_type, linked_note_id, summary, metadata, is_active, last_activity, created_at, updated_at FROM conversations 
WHERE linked_note_id = ?1 
ORDER BY last_activity DESC
`

func (q *Queries) ListConversationsByLinkedNote(ctx context.Context, linkedNoteID sql.NullInt64) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByLinkedNote, linkedNoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AssistantID,
			&i.ConversationType,
			&i.LinkedNoteID,
			&i.Summary,
			&i.Metadata,
			&i.IsActive,
			&i.LastActivity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByType = `-- name: ListConversationsByType :many
SELECT id, title, assistant_id, conversation_type, linked_note_id, summary, metadata, is_active, last_activity, created_at, updated_at FROM conversations 
WHERE conversation_type = ?1 
ORDER BY last_activity DESC
`

func (q *Queries) ListConversationsByType(ctx context.Context, conversationType sql.NullString) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByType, conversationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AssistantID,
			&i.ConversationType,
			&i.LinkedNoteID,
			&i.Summary,
			&i.Metadata,
			&i.IsActive,
			&i.LastActivity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationActive = `-- name: SetConversationActive :exec
UPDATE conversations
SET is_active = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type SetConversationActiveParams struct {
	IsActive sql.NullBool `json:"is_active"`
	ID       int64        `json:"id"`
}

func (q *Queries) SetConversationActive(ctx context.Context, arg SetConversationActiveParams) error {
	_, err := q.db.ExecContext(ctx, setConversationActive, arg.IsActive, arg.ID)
	return err
}

const updateConversationActivity = `-- name: UpdateConversationActivity :exec
UPDATE conversations
SET last_activity = CURRENT_TIMESTAMP
WHERE id = ?1
`

func (q *Queries) UpdateConversationActivity(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateConversationActivity, id)
	return err
}

const updateConversationByID = `-- name: UpdateConversationByID :exec
UPDATE conversations
SET title = ?1,
    assistant_id = ?2,
    conversation_type = ?3,
    linked_note_id = ?4,
    summary = ?5,
    metadata = ?6,
    is_active = ?7,
    last_activity = ?8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?9
`

type UpdateConversationByIDParams struct {
	Title            string         `json:"title"`
	AssistantID      int64          `json:"assistant_id"`
	ConversationType sql.NullString `json:"conversation_type"`
	LinkedNoteID     sql.NullInt64  `json:"linked_note_id"`
	Summary          sql.NullString `json:"summary"`
	Metadata         sql.NullString `json:"metadata"`
	IsActive         sql.NullBool   `json:"is_active"`
	LastActivity     sql.NullTime   `json:"last_activity"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateConversationByID(ctx context.Context, arg UpdateConversationByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationByID,
		arg.Title,
		arg.AssistantID,
		arg.ConversationType,
		arg.LinkedNoteID,
		arg.Summary,
		arg.Metadata,
		arg.IsActive,
		arg.LastActivity,
		arg.ID,
	)
	return err
}
