// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	// ========================================
	// Tag Assignment Operations
	// ========================================
	AddTagToAssistantNote(ctx context.Context, arg AddTagToAssistantNoteParams) error
	CountAssistantNotes(ctx context.Context) (int64, error)
	// Count how many links a note has (useful for finding "hub" notes)
	CountLinksForNote(ctx context.Context, noteID int64) (int64, error)
	CountMessagesByConversation(ctx context.Context, conversationID int64) (int64, error)
	CountTools(ctx context.Context) (int64, error)
	// assistants.sql
	// CRUD operations for assistants table
	// Manages named AI assistants that users create
	// Examples: "My Code Buddy", "Research Assistant", "Writing Helper"
	CreateAssistant(ctx context.Context, arg CreateAssistantParams) (int64, error)
	// assistant_notes.sql
	// CRUD operations for assistant_notes table
	// Assistant's own notes and knowledge base (like user's notes)
	// Follows the same pattern as notes.sql
	CreateAssistantNote(ctx context.Context, arg CreateAssistantNoteParams) (int64, error)
	// assistant_note_links.sql
	// CRUD operations for assistant_note_links table
	// Enables Brain to create knowledge graphs by linking its own notes
	CreateAssistantNoteLink(ctx context.Context, arg CreateAssistantNoteLinkParams) (AssistantNoteLink, error)
	// assistant_note_meta.sql
	// CRUD operations for assistant_note_meta table
	// EAV pattern for flexible key-value pairs on assistant notes
	CreateAssistantNoteMeta(ctx context.Context, arg CreateAssistantNoteMetaParams) error
	// conversations.sql
	// CRUD operations for conversations table
	// Manages chat sessions with assistants
	// Timestamps managed by DB.
	CreateConversation(ctx context.Context, arg CreateConversationParams) (int64, error)
	// messages.sql
	// CRUD operations for messages table
	// Manages chat messages within conversations
	// Uses uuid v7 for ordering. Timestamps managed by DB.
	CreateMessage(ctx context.Context, arg CreateMessageParams) (int64, error)
	// prompts.sql
	// CRUD operations for prompts table
	// Manages reusable system and user prompts
	// Timestamps managed by DB.
	CreatePrompt(ctx context.Context, arg CreatePromptParams) (int64, error)
	// tags.sql
	// CRUD operations for tags table
	// Tags that assistant can use to organize notes
	CreateTag(ctx context.Context, name string) (int64, error)
	CreateTool(ctx context.Context, arg CreateToolParams) (BrainTool, error)
	// Delete all links involving a note (used when deleting a note)
	DeleteAllLinksForNote(ctx context.Context, noteID int64) error
	DeleteAssistantByID(ctx context.Context, id int64) error
	DeleteAssistantNoteByID(ctx context.Context, id int64) error
	DeleteAssistantNoteLink(ctx context.Context, id int64) error
	// Delete all links between two specific notes
	DeleteAssistantNoteLinksBetween(ctx context.Context, arg DeleteAssistantNoteLinksBetweenParams) error
	DeleteAssistantNoteMetaByID(ctx context.Context, id int64) error
	DeleteAssistantNoteMetaByKey(ctx context.Context, arg DeleteAssistantNoteMetaByKeyParams) error
	DeleteAssistantNotesByLinkedNote(ctx context.Context, relatedNoteID sql.NullInt64) error
	DeleteConversationByID(ctx context.Context, id int64) error
	DeleteMessageByID(ctx context.Context, id int64) error
	DeleteMessagesByConversation(ctx context.Context, conversationID int64) error
	DeletePromptByID(ctx context.Context, id int64) error
	DeleteTagByID(ctx context.Context, id int64) error
	DeleteTool(ctx context.Context, uuid string) error
	// Find notes with many connections (knowledge hubs)
	FindStronglyConnectedNotes(ctx context.Context, limitCount int64) ([]FindStronglyConnectedNotesRow, error)
	GetAllTools(ctx context.Context) ([]BrainTool, error)
	GetAssistantByID(ctx context.Context, id int64) (Assistant, error)
	GetAssistantByName(ctx context.Context, name string) (Assistant, error)
	GetAssistantNoteByID(ctx context.Context, id int64) (AssistantNote, error)
	// assistant_notes_search.sql
	// Search and related queries for assistant_notes
	// NOTE: FTS5 queries are in internal/brain/store/fts_queries.go (SQLC can't handle FTS5 virtual tables)
	// Get a single assistant note with minimal fields for RAG context
	GetAssistantNoteByIDForRAG(ctx context.Context, id int64) (GetAssistantNoteByIDForRAGRow, error)
	GetAssistantNoteByUUID(ctx context.Context, uuid string) (AssistantNote, error)
	GetAssistantNoteLinkByID(ctx context.Context, id int64) (AssistantNoteLink, error)
	GetAssistantNoteMetaByID(ctx context.Context, id int64) (AssistantNoteMetum, error)
	GetAssistantNoteMetaByKey(ctx context.Context, arg GetAssistantNoteMetaByKeyParams) (AssistantNoteMetum, error)
	// ========================================
	// Composite Queries - Assistants with Relations
	// ========================================
	GetAssistantWithPrompt(ctx context.Context, id int64) (GetAssistantWithPromptRow, error)
	// Get all notes linked TO this note
	GetBacklinks(ctx context.Context, destNoteID int64) ([]GetBacklinksRow, error)
	// Get all notes connected to this note (both directions)
	GetBidirectionalLinks(ctx context.Context, noteID int64) ([]GetBidirectionalLinksRow, error)
	GetConversationByID(ctx context.Context, id int64) (Conversation, error)
	GetConversationHistory(ctx context.Context, conversationID int64) ([]GetConversationHistoryRow, error)
	// ========================================
	// Composite Queries - Conversations with Relations
	// ========================================
	GetConversationWithAssistant(ctx context.Context, id int64) (GetConversationWithAssistantRow, error)
	GetConversationWithDetails(ctx context.Context, id int64) (GetConversationWithDetailsRow, error)
	// Get all notes linked FROM this note
	GetForwardLinks(ctx context.Context, srcNoteID int64) ([]GetForwardLinksRow, error)
	GetLatestMessageByConversation(ctx context.Context, conversationID int64) (Message, error)
	// Get all links created by a specific assistant
	GetLinksByAssistant(ctx context.Context, createdByAssistantID sql.NullInt64) ([]GetLinksByAssistantRow, error)
	// Get all links of a specific type
	GetLinksByType(ctx context.Context, linkType string) ([]GetLinksByTypeRow, error)
	GetMessageByID(ctx context.Context, id int64) (Message, error)
	GetMessageByUUID(ctx context.Context, uuid string) (Message, error)
	// ========================================
	// Composite Queries - Messages with Relations
	// ========================================
	GetMessageWithConversation(ctx context.Context, id int64) (GetMessageWithConversationRow, error)
	GetPromptByID(ctx context.Context, id int64) (Prompt, error)
	GetPromptByTitle(ctx context.Context, title string) (Prompt, error)
	GetRecentConversations(ctx context.Context, sinceDate sql.NullTime) ([]Conversation, error)
	// Find assistant notes linking to this note (backward links)
	GetRelatedAssistantNotesByBackwardLinks(ctx context.Context, arg GetRelatedAssistantNotesByBackwardLinksParams) ([]GetRelatedAssistantNotesByBackwardLinksRow, error)
	// Find assistant notes linked from this note (forward links)
	GetRelatedAssistantNotesByForwardLinks(ctx context.Context, arg GetRelatedAssistantNotesByForwardLinksParams) ([]GetRelatedAssistantNotesByForwardLinksRow, error)
	// Find all observations related to the same source Mind note
	GetRelatedAssistantNotesBySourceNote(ctx context.Context, arg GetRelatedAssistantNotesBySourceNoteParams) ([]GetRelatedAssistantNotesBySourceNoteRow, error)
	// Find assistant notes with shared tags
	GetRelatedAssistantNotesByTags(ctx context.Context, arg GetRelatedAssistantNotesByTagsParams) ([]GetRelatedAssistantNotesByTagsRow, error)
	GetTagByID(ctx context.Context, id int64) (Tag, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	// brain_tools stores available tools that Brain can execute
	// These are seeded with core operations and can be dynamically queried
	// by the small model to match user intent to executable tools
	GetToolByName(ctx context.Context, name string) (BrainTool, error)
	GetToolByUUID(ctx context.Context, uuid string) (BrainTool, error)
	GetToolsByType(ctx context.Context, toolType string) ([]BrainTool, error)
	ListActiveAssistantNotes(ctx context.Context) ([]AssistantNote, error)
	ListActiveAssistants(ctx context.Context) ([]Assistant, error)
	ListActiveConversations(ctx context.Context) ([]Conversation, error)
	ListAssistantNoteMetaByNoteID(ctx context.Context, assistantNoteID int64) ([]AssistantNoteMetum, error)
	ListAssistantNotes(ctx context.Context) ([]AssistantNote, error)
	ListAssistantNotesByAssistant(ctx context.Context, createdByAssistantID sql.NullInt64) ([]AssistantNote, error)
	ListAssistantNotesByConversation(ctx context.Context, relatedConversationID sql.NullInt64) ([]AssistantNote, error)
	ListAssistantNotesByLinkedNote(ctx context.Context, relatedNoteID sql.NullInt64) ([]AssistantNote, error)
	ListAssistantNotesByMetaKey(ctx context.Context, key string) ([]AssistantNote, error)
	ListAssistantNotesByPriority(ctx context.Context, minPriority sql.NullInt64) ([]AssistantNote, error)
	ListAssistantNotesByTag(ctx context.Context, tagID int64) ([]AssistantNote, error)
	ListAssistantNotesByType(ctx context.Context, noteType sql.NullString) ([]AssistantNote, error)
	ListAssistants(ctx context.Context) ([]Assistant, error)
	ListAssistantsByProviderType(ctx context.Context, providerType string) ([]Assistant, error)
	ListConversations(ctx context.Context) ([]Conversation, error)
	ListConversationsByAssistant(ctx context.Context, assistantID int64) ([]Conversation, error)
	ListConversationsByLinkedNote(ctx context.Context, linkedNoteID sql.NullInt64) ([]Conversation, error)
	ListConversationsByType(ctx context.Context, conversationType sql.NullString) ([]Conversation, error)
	ListMessages(ctx context.Context) ([]Message, error)
	ListMessagesByConversation(ctx context.Context, conversationID int64) ([]Message, error)
	ListMessagesByRole(ctx context.Context, role string) ([]Message, error)
	ListPendingTasks(ctx context.Context) ([]AssistantNote, error)
	ListPrompts(ctx context.Context) ([]Prompt, error)
	ListPromptsByCategory(ctx context.Context, category sql.NullString) ([]Prompt, error)
	ListSystemPrompts(ctx context.Context) ([]Prompt, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsByAssistantNote(ctx context.Context, assistantNoteID int64) ([]Tag, error)
	ListUpcomingReminders(ctx context.Context, beforeDate sql.NullTime) ([]AssistantNote, error)
	ListUserPrompts(ctx context.Context) ([]Prompt, error)
	MarkAssistantNoteCompleted(ctx context.Context, id int64) error
	RemoveTagFromAssistantNote(ctx context.Context, arg RemoveTagFromAssistantNoteParams) error
	// Brain's LLM will use tool descriptions to select appropriate tools
	SearchToolsByDescription(ctx context.Context, dollar_1 sql.NullString) ([]BrainTool, error)
	SetAssistantActive(ctx context.Context, arg SetAssistantActiveParams) error
	SetAssistantNoteActive(ctx context.Context, arg SetAssistantNoteActiveParams) error
	SetConversationActive(ctx context.Context, arg SetConversationActiveParams) error
	UpdateAssistantByID(ctx context.Context, arg UpdateAssistantByIDParams) error
	UpdateAssistantNoteByID(ctx context.Context, arg UpdateAssistantNoteByIDParams) error
	UpdateAssistantNoteLink(ctx context.Context, arg UpdateAssistantNoteLinkParams) error
	UpdateAssistantNoteMetaByID(ctx context.Context, arg UpdateAssistantNoteMetaByIDParams) error
	UpdateConversationActivity(ctx context.Context, id int64) error
	UpdateConversationByID(ctx context.Context, arg UpdateConversationByIDParams) error
	UpdateMessageByID(ctx context.Context, arg UpdateMessageByIDParams) error
	UpdatePromptByID(ctx context.Context, arg UpdatePromptByIDParams) error
	UpdateTool(ctx context.Context, arg UpdateToolParams) error
}

var _ Querier = (*Queries)(nil)
