name: Bug Report
description: Report a bug or unexpected behavior
labels: ["type: bug", "status: triage", "priority: medium"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system is affected?
      options:
        - mind (Notes/PKM service)
        - brain (AI/Assistant service)
        - api (Connect RPC endpoints)
        - proto (Protocol buffers)
        - shared (Shared packages)
        - ci/cd (GitHub Actions)
        - other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug
      placeholder: Describe what went wrong
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Logs, screenshots, environment details, etc.
      placeholder: Any other relevant information
    validations:
      required: false
