// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	// ========================================
	// System Collection Protection
	// ========================================
	CheckIfSystemCollection(ctx context.Context, id int64) (bool, error)
	// ========================================
	// System Type Protection
	// ========================================
	CheckIfSystemType(ctx context.Context, id int64) (bool, error)
	CountBrokenLinks(ctx context.Context) (int64, error)
	CountCollections(ctx context.Context) (int64, error)
	CountCollectionsByParent(ctx context.Context, parentID interface{}) (int64, error)
	CountNoteTypes(ctx context.Context) (int64, error)
	CountNotes(ctx context.Context) (int64, error)
	CountNotesByCollectionID(ctx context.Context, collectionID int64) (int64, error)
	CountNotesByIsTemplate(ctx context.Context, isTemplate sql.NullBool) (int64, error)
	CountNotesByNoteTypeID(ctx context.Context, noteTypeID sql.NullInt64) (int64, error)
	CountNotesInCollection(ctx context.Context, collectionID int64) (int64, error)
	CountTags(ctx context.Context) (int64, error)
	CountTagsForNote(ctx context.Context, noteID int64) (int64, error)
	CountTemplates(ctx context.Context) (int64, error)
	CountUnresolvedLinks(ctx context.Context) (int64, error)
	// collections.sql
	// CRUD operations for collections (hierarchical folders/paths for notes)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (int64, error)
	// notes.sql
	// Pass 4: CRUD + composite queries for notes (SQLite, sqlc compatible)
	// sqlc annotations added for code generation
	// NOTE: uuid field uses uuidv7. Ordering by uuid. Timestamps managed by DB.
	// Included: insert, select by id, select all, update by id, delete by id, composite queries
	// Next: Add more composite queries for tags and FTS integration
	CreateNote(ctx context.Context, arg CreateNoteParams) (int64, error)
	CreateNoteMeta(ctx context.Context, arg CreateNoteMetaParams) (int64, error)
	CreateNoteTag(ctx context.Context, arg CreateNoteTagParams) error
	// note_types.sql
	// Pass 4: CRUD + filter queries for note_types (SQLite, sqlc compatible)
	// sqlc annotations added for code generation
	// Included: insert, select by id, select all, update by id, delete by id, filter by type(s)
	// Next: Add composite queries with notes count per type
	CreateNoteType(ctx context.Context, arg CreateNoteTypeParams) (int64, error)
	CreateNotesLink(ctx context.Context, arg CreateNotesLinkParams) (int64, error)
	// tags.sql
	// Pass 3: CRUD + advanced queries for tags and note_tags (SQLite, sqlc compatible)
	// sqlc annotations added for code generation
	// Included: insert, select by id, select all, update by id, delete by id, advanced queries for tag search and usage
	// Next: Consider more advanced tag suggestions, filtering, and usage analytics
	CreateTag(ctx context.Context, name string) (int64, error)
	// templates.sql
	// Pass 3: CRUD for templates (SQLite, sqlc compatible)
	// sqlc annotations added for code generation
	// Timestamps managed by DB. TODO: Revisit note_type_id FK.
	// Included: insert, select by id, select all, update by id, delete by id
	// Note: Search queries removed - use general search with filters instead
	// Next: Add advanced queries if needed (filter by note_type, etc.)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (int64, error)
	CreateUnresolvedNotesLink(ctx context.Context, arg CreateUnresolvedNotesLinkParams) (int64, error)
	DeleteCollection(ctx context.Context, id int64) error
	DeleteNoteByID(ctx context.Context, id int64) error
	DeleteNoteMetaByID(ctx context.Context, id int64) error
	DeleteNoteMetaByNoteID(ctx context.Context, noteID int64) error
	DeleteNoteTag(ctx context.Context, arg DeleteNoteTagParams) error
	DeleteNoteTagsByNoteID(ctx context.Context, noteID int64) error
	DeleteNoteTypeByID(ctx context.Context, id int64) error
	DeleteNotesLinksBySrcID(ctx context.Context, srcID int64) error
	DeleteTagByID(ctx context.Context, id int64) error
	DeleteTemplateByID(ctx context.Context, id int64) error
	// This is a helper query to find existing collection by path
	// or return NULL if not found (actual creation happens in Go code)
	FindOrCreateCollectionByPath(ctx context.Context, path string) (Collection, error)
	// Finds unresolved links that point to a specific note title
	// Used when creating a note to resolve pending links
	FindUnresolvedLinksByDestTitle(ctx context.Context, destTitle sql.NullString) ([]NotesLink, error)
	// Get all ancestors of a collection by walking up the parent_id chain
	GetCollectionAncestors(ctx context.Context, collectionID int64) ([]GetCollectionAncestorsRow, error)
	GetCollectionByID(ctx context.Context, id int64) (Collection, error)
	GetCollectionByPath(ctx context.Context, path string) (Collection, error)
	GetCollectionChildren(ctx context.Context, parentID interface{}) ([]Collection, error)
	// Get all descendants of a collection by walking down the parent_id chain
	GetCollectionDescendants(ctx context.Context, collectionID int64) ([]GetCollectionDescendantsRow, error)
	GetCollectionStats(ctx context.Context) ([]GetCollectionStatsRow, error)
	GetNoteByID(ctx context.Context, id int64) (Note, error)
	// notes_search.sql
	// Search and related queries for notes
	// NOTE: FTS5 queries are in internal/mind/store/fts_queries.go (SQLC can't handle FTS5 virtual tables)
	// Get a single note with minimal fields for RAG context
	GetNoteByIDForRAG(ctx context.Context, id int64) (GetNoteByIDForRAGRow, error)
	GetNoteByTitle(ctx context.Context, arg GetNoteByTitleParams) (Note, error)
	// For wikilink resolution: searches by title across all collections
	// Returns first match (undefined order if multiple collections have same title)
	GetNoteByTitleGlobal(ctx context.Context, title string) (Note, error)
	// Lookup note by title within a specific collection (titles unique per collection)
	GetNoteByTitleInCollection(ctx context.Context, arg GetNoteByTitleInCollectionParams) (Note, error)
	GetNoteByUUID(ctx context.Context, argUuid uuid.UUID) (Note, error)
	GetNoteMetaByID(ctx context.Context, id int64) (NoteMetum, error)
	// ========================================
	// Composite Queries - Note Meta with Notes
	// ========================================
	GetNoteMetaByNoteID(ctx context.Context, noteID int64) ([]NoteMetum, error)
	GetNoteTypeByID(ctx context.Context, id int64) (NoteType, error)
	GetNoteTypeByType(ctx context.Context, type_ string) (NoteType, error)
	// ========================================
	// Composite Queries - Note Types with Notes
	// ========================================
	GetNoteTypeWithNotesCount(ctx context.Context, id int64) (GetNoteTypeWithNotesCountRow, error)
	GetNoteTypesByTypes(ctx context.Context, types string) ([]NoteType, error)
	// ========================================
	// Composite Query - Note with All Relations
	// ========================================
	GetNoteWithAllRelationsByID(ctx context.Context, id int64) (GetNoteWithAllRelationsByIDRow, error)
	// ========================================
	// Composite Queries - Notes with Relations
	// ========================================
	GetNoteWithMetaByID(ctx context.Context, id int64) (GetNoteWithMetaByIDRow, error)
	GetNoteWithTypeByID(ctx context.Context, id int64) (GetNoteWithTypeByIDRow, error)
	GetNotesLinkByID(ctx context.Context, id int64) (NotesLink, error)
	// ========================================
	// Composite Queries - Notes Links with Note Details
	// ========================================
	GetNotesLinkWithNoteTitles(ctx context.Context, id int64) (GetNotesLinkWithNoteTitlesRow, error)
	// Find notes linking to this note (backward links)
	GetRelatedNotesByBackwardLinks(ctx context.Context, arg GetRelatedNotesByBackwardLinksParams) ([]GetRelatedNotesByBackwardLinksRow, error)
	// Find notes linked from this note (forward links)
	GetRelatedNotesByForwardLinks(ctx context.Context, arg GetRelatedNotesByForwardLinksParams) ([]GetRelatedNotesByForwardLinksRow, error)
	// Find notes with shared tags
	GetRelatedNotesByTags(ctx context.Context, arg GetRelatedNotesByTagsParams) ([]GetRelatedNotesByTagsRow, error)
	GetTagByID(ctx context.Context, id int64) (Tag, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTemplateByID(ctx context.Context, id int64) (Template, error)
	ListBrokenLinks(ctx context.Context) ([]NotesLink, error)
	ListCollections(ctx context.Context) ([]Collection, error)
	ListCollectionsByParent(ctx context.Context, parentID interface{}) ([]Collection, error)
	ListCollectionsByParentPaginated(ctx context.Context, arg ListCollectionsByParentPaginatedParams) ([]Collection, error)
	// ========================================
	// Paginated Queries (AIP-158)
	// ========================================
	ListCollectionsPaginated(ctx context.Context, arg ListCollectionsPaginatedParams) ([]Collection, error)
	ListDistinctNoteMetaKeys(ctx context.Context) ([]string, error)
	ListNoteMeta(ctx context.Context) ([]NoteMetum, error)
	// note_meta.sql
	// Pass 4: CRUD + advanced queries for note_meta (SQLite, sqlc compatible)
	// sqlc annotations added for code generation
	// Timestamps managed by DB. Optimized with composite index (note_id, key).
	// Included: insert, select by id, select all, update by id, delete by id, advanced queries
	// UPSERT support added for bulk meta operations
	ListNoteMetaByKey(ctx context.Context, key string) ([]NoteMetum, error)
	ListNoteMetaByKeyValuePattern(ctx context.Context, arg ListNoteMetaByKeyValuePatternParams) ([]NoteMetum, error)
	ListNoteMetaByKeys(ctx context.Context, keys string) ([]NoteMetum, error)
	ListNoteTags(ctx context.Context) ([]NoteTag, error)
	ListNoteTagsByNoteID(ctx context.Context, noteID int64) ([]NoteTag, error)
	ListNoteTagsByTagID(ctx context.Context, tagID int64) ([]NoteTag, error)
	ListNoteTypes(ctx context.Context) ([]NoteType, error)
	// ========================================
	// Paginated Queries (AIP-158)
	// ========================================
	ListNoteTypesPaginated(ctx context.Context, arg ListNoteTypesPaginatedParams) ([]NoteType, error)
	ListNoteTypesWithCount(ctx context.Context) ([]ListNoteTypesWithCountRow, error)
	ListNotes(ctx context.Context) ([]Note, error)
	// ========================================
	// Collection Queries
	// ========================================
	ListNotesByCollectionID(ctx context.Context, collectionID int64) ([]Note, error)
	ListNotesByCollectionIDPaginated(ctx context.Context, arg ListNotesByCollectionIDPaginatedParams) ([]Note, error)
	ListNotesByCollectionPath(ctx context.Context, path string) ([]Note, error)
	ListNotesByIsTemplatePaginated(ctx context.Context, arg ListNotesByIsTemplatePaginatedParams) ([]Note, error)
	ListNotesByMetaKeys(ctx context.Context, key string) ([]Note, error)
	ListNotesByNoteTypeID(ctx context.Context, noteTypeID sql.NullInt64) ([]Note, error)
	ListNotesByNoteTypeIDPaginated(ctx context.Context, arg ListNotesByNoteTypeIDPaginatedParams) ([]Note, error)
	// ========================================
	// Filter Queries - Notes by Relations
	// ========================================
	ListNotesByTagIDs(ctx context.Context, tagID int64) ([]Note, error)
	// ========================================
	// Multi-Tag Filtering (FR-TAGS-02)
	// ========================================
	// Returns notes that have ALL specified tags (intersection)
	// Example: tag_ids = [1,2,3] returns notes tagged with 1 AND 2 AND 3
	// Implementation: COUNT(DISTINCT tag_id) must equal number of requested tags
	ListNotesByTagIDsAND(ctx context.Context, arg ListNotesByTagIDsANDParams) ([]Note, error)
	// Returns notes that have ANY of the specified tags (union)
	// Example: tag_ids = [1,2,3] returns notes tagged with 1 OR 2 OR 3
	ListNotesByTagIDsOR(ctx context.Context, tagIds []int64) ([]Note, error)
	ListNotesForTag(ctx context.Context, tagID int64) ([]Note, error)
	ListNotesLinks(ctx context.Context) ([]NotesLink, error)
	ListNotesLinksByDestID(ctx context.Context, destID sql.NullInt64) ([]NotesLink, error)
	// Batch query for multiple notes (graph view construction)
	// Example usage: GetLinks for notes 1,2,3 to build subgraph
	ListNotesLinksByNoteIDs(ctx context.Context, noteIds []int64) ([]NotesLink, error)
	// TODO: Add composite queries with note titles for display
	ListNotesLinksBySrcID(ctx context.Context, srcID int64) ([]NotesLink, error)
	// ========================================
	// Paginated Queries (AIP-158)
	// ========================================
	ListNotesPaginated(ctx context.Context, arg ListNotesPaginatedParams) ([]Note, error)
	// ========================================
	// Additional Query Patterns (FR-LINKS-02)
	// ========================================
	// Returns links where destination note no longer exists (dest_id IS NULL)
	// Used for "broken links" UI view (BR-03: Knowledge Preservation)
	ListOrphanedLinks(ctx context.Context) ([]NotesLink, error)
	ListRootCollections(ctx context.Context) ([]Collection, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsForNote(ctx context.Context, noteID int64) ([]Tag, error)
	ListTagsForNotePaginated(ctx context.Context, arg ListTagsForNotePaginatedParams) ([]Tag, error)
	// ========================================
	// Paginated Queries (AIP-158)
	// ========================================
	ListTagsPaginated(ctx context.Context, arg ListTagsPaginatedParams) ([]Tag, error)
	ListTemplates(ctx context.Context) ([]Template, error)
	// ========================================
	// Paginated Queries (AIP-158)
	// ========================================
	ListTemplatesPaginated(ctx context.Context, arg ListTemplatesPaginatedParams) ([]Template, error)
	// ========================================
	// WikiLink Resolution Queries
	// ========================================
	// Gets both pending (0) and broken (-1) links for resolution
	// Broken links can become resolved if the target note is created later
	ListUnresolvedLinks(ctx context.Context, limit int64) ([]NotesLink, error)
	MarkLinkBroken(ctx context.Context, id int64) error
	// Resolves a pending link by setting dest_id and clearing dest_title
	// dest_title is only kept for unresolved (0) and broken (-1) links
	ResolveLink(ctx context.Context, arg ResolveLinkParams) error
	SearchNotesLinksByDisplayText(ctx context.Context, displayTextPattern sql.NullString) ([]NotesLink, error)
	SearchTagsByName(ctx context.Context, namePattern string) ([]Tag, error)
	TagUsageCount(ctx context.Context) ([]TagUsageCountRow, error)
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error
	UpdateNoteByID(ctx context.Context, arg UpdateNoteByIDParams) error
	UpdateNoteMetaByID(ctx context.Context, arg UpdateNoteMetaByIDParams) error
	UpdateNoteTypeByID(ctx context.Context, arg UpdateNoteTypeByIDParams) error
	UpdateTagByID(ctx context.Context, arg UpdateTagByIDParams) error
	UpdateTemplateByID(ctx context.Context, arg UpdateTemplateByIDParams) error
	UpsertNoteMeta(ctx context.Context, arg UpsertNoteMetaParams) error
}

var _ Querier = (*Queries)(nil)
