// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package store

import (
	"context"
	"database/sql"
)

const countTemplates = `-- name: CountTemplates :one
SELECT COUNT(*) FROM templates
`

func (q *Queries) CountTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :execlastid

INSERT INTO templates (name, description, starter_note_id, note_type_id)
VALUES (?1, ?2, ?3, ?4)
`

type CreateTemplateParams struct {
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	StarterNoteID int64          `json:"starter_note_id"`
	NoteTypeID    sql.NullInt64  `json:"note_type_id"`
}

// templates.sql
// Pass 3: CRUD for templates (SQLite, sqlc compatible)
// sqlc annotations added for code generation
// Timestamps managed by DB. TODO: Revisit note_type_id FK.
// Included: insert, select by id, select all, update by id, delete by id
// Note: Search queries removed - use general search with filters instead
// Next: Add advanced queries if needed (filter by note_type, etc.)
func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTemplate,
		arg.Name,
		arg.Description,
		arg.StarterNoteID,
		arg.NoteTypeID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteTemplateByID = `-- name: DeleteTemplateByID :exec
DELETE FROM templates WHERE id = ?1
`

func (q *Queries) DeleteTemplateByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateByID, id)
	return err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, name, description, starter_note_id, note_type_id, created_at, updated_at FROM templates WHERE id = ?1
`

func (q *Queries) GetTemplateByID(ctx context.Context, id int64) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByID, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StarterNoteID,
		&i.NoteTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, description, starter_note_id, note_type_id, created_at, updated_at FROM templates ORDER BY id
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.StarterNoteID,
			&i.NoteTypeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesPaginated = `-- name: ListTemplatesPaginated :many

SELECT id, name, description, starter_note_id, note_type_id, created_at, updated_at FROM templates 
ORDER BY id
LIMIT ?2 OFFSET ?1
`

type ListTemplatesPaginatedParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

// ========================================
// Paginated Queries (AIP-158)
// ========================================
func (q *Queries) ListTemplatesPaginated(ctx context.Context, arg ListTemplatesPaginatedParams) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplatesPaginated, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.StarterNoteID,
			&i.NoteTypeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplateByID = `-- name: UpdateTemplateByID :exec
UPDATE templates
SET name = ?1,
    description = ?2,
    starter_note_id = ?3,
    note_type_id = ?4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?5
`

type UpdateTemplateByIDParams struct {
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	StarterNoteID int64          `json:"starter_note_id"`
	NoteTypeID    sql.NullInt64  `json:"note_type_id"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateTemplateByID(ctx context.Context, arg UpdateTemplateByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplateByID,
		arg.Name,
		arg.Description,
		arg.StarterNoteID,
		arg.NoteTypeID,
		arg.ID,
	)
	return err
}
