// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: conversations.sql

package store

import (
	"context"
	"database/sql"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (uuid, actor_id, title, description, metadata, is_active) 
VALUES (?, ?, ?, ?, ?, ?) 
RETURNING id, uuid, actor_id, title, description, metadata, is_active, created_at, updated_at
`

type CreateConversationParams struct {
	Uuid        string         `json:"uuid"`
	ActorID     int64          `json:"actor_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Metadata    sql.NullString `json:"metadata"`
	IsActive    sql.NullBool   `json:"is_active"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.Uuid,
		arg.ActorID,
		arg.Title,
		arg.Description,
		arg.Metadata,
		arg.IsActive,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ActorID,
		&i.Title,
		&i.Description,
		&i.Metadata,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, uuid, actor_id, title, description, metadata, is_active, created_at, updated_at 
FROM conversations 
WHERE id = ? 
LIMIT 1
`

func (q *Queries) GetConversationByID(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ActorID,
		&i.Title,
		&i.Description,
		&i.Metadata,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByUUID = `-- name: GetConversationByUUID :one
SELECT id, uuid, actor_id, title, description, metadata, is_active, created_at, updated_at 
FROM conversations 
WHERE uuid = ? 
LIMIT 1
`

func (q *Queries) GetConversationByUUID(ctx context.Context, uuid string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByUUID, uuid)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ActorID,
		&i.Title,
		&i.Description,
		&i.Metadata,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationsByActorID = `-- name: GetConversationsByActorID :many
SELECT id, uuid, actor_id, title, description, metadata, is_active, created_at, updated_at 
FROM conversations 
WHERE actor_id = ? AND is_active = true 
ORDER BY created_at DESC
`

func (q *Queries) GetConversationsByActorID(ctx context.Context, actorID int64) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, getConversationsByActorID, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ActorID,
			&i.Title,
			&i.Description,
			&i.Metadata,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :exec
UPDATE conversations 
SET title = ?, description = ?, metadata = ?, is_active = ?, updated_at = CURRENT_TIMESTAMP 
WHERE id = ?
`

type UpdateConversationParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Metadata    sql.NullString `json:"metadata"`
	IsActive    sql.NullBool   `json:"is_active"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) error {
	_, err := q.db.ExecContext(ctx, updateConversation,
		arg.Title,
		arg.Description,
		arg.Metadata,
		arg.IsActive,
		arg.ID,
	)
	return err
}
