// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
)

type Actor struct {
	ID          int64          `json:"id"`
	Type        string         `json:"type"`
	Name        string         `json:"name"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Metadata    sql.NullString `json:"metadata"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Chat struct {
	ID             int64          `json:"id"`
	Uuid           string         `json:"uuid"`
	ConversationID int64          `json:"conversation_id"`
	ActorID        int64          `json:"actor_id"`
	Title          string         `json:"title"`
	ProviderID     sql.NullInt64  `json:"provider_id"`
	ModelName      sql.NullString `json:"model_name"`
	SystemPromptID sql.NullInt64  `json:"system_prompt_id"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type Conversation struct {
	ID          int64          `json:"id"`
	ActorID     int64          `json:"actor_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Metadata    sql.NullString `json:"metadata"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Model struct {
	ID            int64          `json:"id"`
	ProviderID    sql.NullInt64  `json:"provider_id"`
	Name          string         `json:"name"`
	Capabilities  sql.NullString `json:"capabilities"`
	DefaultParams sql.NullString `json:"default_params"`
	IsActive      sql.NullBool   `json:"is_active"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Prompt struct {
	ID        int64          `json:"id"`
	ActorID   sql.NullInt64  `json:"actor_id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	IsSystem  sql.NullInt64  `json:"is_system"`
	CreatedAt sql.NullString `json:"created_at"`
	UpdatedAt sql.NullString `json:"updated_at"`
}

type Provider struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Type      string       `json:"type"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type ProviderSetting struct {
	ID           int64         `json:"id"`
	ProviderID   sql.NullInt64 `json:"provider_id"`
	SettingKey   string        `json:"setting_key"`
	SettingValue string        `json:"setting_value"`
	IsSecret     sql.NullBool  `json:"is_secret"`
	CreatedAt    sql.NullTime  `json:"created_at"`
}
