// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
)

type Actor struct {
	ID          int64          `json:"id"`
	Type        string         `json:"type"`
	Name        string         `json:"name"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsActive    sql.NullBool   `json:"is_active"`
	Metadata    sql.NullString `json:"metadata"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Conversation struct {
	ID          int64          `json:"id"`
	ActorID     int64          `json:"actor_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
	Metadata    sql.NullString `json:"metadata"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type LlmService struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	Adapter       string         `json:"adapter"`
	ApiKey        string         `json:"api_key"`
	BaseUrl       string         `json:"base_url"`
	Organization  sql.NullString `json:"organization"`
	Configuration string         `json:"configuration"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Message struct {
	ID             int64          `json:"id"`
	ConversationID int64          `json:"conversation_id"`
	SenderActorID  int64          `json:"sender_actor_id"`
	Uuid           string         `json:"uuid"`
	Content        string         `json:"content"`
	MessageType    sql.NullString `json:"message_type"`
	Metadata       sql.NullString `json:"metadata"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Prompt struct {
	ID        int64          `json:"id"`
	ActorID   sql.NullInt64  `json:"actor_id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	IsSystem  sql.NullInt64  `json:"is_system"`
	CreatedAt sql.NullString `json:"created_at"`
	UpdatedAt sql.NullString `json:"updated_at"`
}

type Provider struct {
	ID             int64         `json:"id"`
	LlmServiceID   sql.NullInt64 `json:"llm_service_id"`
	SystemPromptID sql.NullInt64 `json:"system_prompt_id"`
	Name           string        `json:"name"`
	Description    string        `json:"description"`
	CreatedAt      sql.NullTime  `json:"created_at"`
}
