// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateActor(ctx context.Context, arg CreateActorParams) (Actor, error)
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateLLMService(ctx context.Context, arg CreateLLMServiceParams) (LlmService, error)
	CreatePrompt(ctx context.Context, arg CreatePromptParams) error
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	DeleteActor(ctx context.Context, id int64) error
	DeleteChat(ctx context.Context, id int64) error
	DeleteConversation(ctx context.Context, id int64) error
	DeleteLLMService(ctx context.Context, id int64) error
	DeletePrompt(ctx context.Context, id int64) error
	DeleteProvider(ctx context.Context, id int64) error
	GetActorByID(ctx context.Context, id int64) (Actor, error)
	GetActorByName(ctx context.Context, arg GetActorByNameParams) (Actor, error)
	GetActorsByType(ctx context.Context, type_ string) ([]Actor, error)
	GetAllLLMServices(ctx context.Context) ([]LlmService, error)
	GetAllPrompts(ctx context.Context) ([]Prompt, error)
	GetAllProviders(ctx context.Context) ([]GetAllProvidersRow, error)
	GetChatByID(ctx context.Context, id int64) (Chat, error)
	GetChatByUUID(ctx context.Context, uuid string) (Chat, error)
	GetChatWithProviderDetails(ctx context.Context, id int64) (GetChatWithProviderDetailsRow, error)
	GetChatsByActorID(ctx context.Context, actorID int64) ([]Chat, error)
	GetChatsByConversationID(ctx context.Context, conversationID int64) ([]Chat, error)
	GetConversationByID(ctx context.Context, id int64) (Conversation, error)
	GetConversationsByActorID(ctx context.Context, actorID int64) ([]Conversation, error)
	GetLLMServiceByID(ctx context.Context, id int64) (LlmService, error)
	GetLLMServiceByName(ctx context.Context, name string) (LlmService, error)
	GetPromptById(ctx context.Context, id int64) (Prompt, error)
	GetPromptsByActorID(ctx context.Context, actorID sql.NullInt64) ([]Prompt, error)
	GetProviderByID(ctx context.Context, id int64) (GetProviderByIDRow, error)
	GetProviderByName(ctx context.Context, name string) (GetProviderByNameRow, error)
	GetProvidersByLLMService(ctx context.Context, llmServiceID sql.NullInt64) ([]GetProvidersByLLMServiceRow, error)
	GetSystemPrompts(ctx context.Context) ([]Prompt, error)
	UpdateActor(ctx context.Context, arg UpdateActorParams) error
	UpdateChatTitle(ctx context.Context, arg UpdateChatTitleParams) error
	UpdateConversation(ctx context.Context, arg UpdateConversationParams) error
	UpdateLLMService(ctx context.Context, arg UpdateLLMServiceParams) error
	UpdatePrompt(ctx context.Context, arg UpdatePromptParams) error
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) error
}

var _ Querier = (*Queries)(nil)
