// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/nkapatos/mindweaver/internal/templates/layouts"

func Chat(activePath string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto p-4\"><h1 class=\"text-3xl font-bold mb-6 text-center\">Chats</h1><div class=\"chat chat-start bg-base-200 rounded-lg shadow-md p-4 mb-4\"><div class=\"chat-image avatar\"><div class=\"w-10 rounded-full\"><img src=\"https://placeimg.com/192/192/people\" alt=\"User Avatar\"></div></div><div class=\"chat-header flex items-center gap-2\"><span class=\"font-semibold text-lg\">Alice</span> <time class=\"text-xs opacity-50\">12:45 PM</time></div><div class=\"chat-bubble\">Hi! How are you?</div></div><div class=\"chat chat-end bg-base-200 rounded-lg shadow-md p-4 mb-4\"><div class=\"chat-header flex items-center gap-2 justify-end\"><time class=\"text-xs opacity-50\">12:46 PM</time> <span class=\"font-semibold text-lg\">You</span></div><div class=\"chat-bubble\">Hello Alice! I'm good, thanks. How about you?</div><div class=\"chat-image avatar\"><div class=\"w-10 rounded-full\"><img src=\"https://placeimg.com/192/192/people?2\" alt=\"Your Avatar\"></div></div></div><form class=\"mt-6 flex gap-2\" onsubmit=\"event.preventDefault(); /* handle submit here */\"><input type=\"text\" placeholder=\"Type your message here...\" class=\"input input-bordered flex-grow\" autocomplete=\"off\" required> <button type=\"submit\" class=\"btn btn-primary\">Send</button></form></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.AppLayout("Chats", "chat stuff here", activePath).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
